# Generated by Django 4.0.3 on 2022-03-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('type', models.CharField(max_length=7)),
                ('price', models.CharField(max_length=45)),
                ('date', models.DateTimeField(default='2022-03-12', verbose_name='date created')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
