# Generated by Django 4.0.3 on 2022-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default='2022-03-13', verbose_name='date created'),
        ),
    ]
