# Generated by Django 4.0.3 on 2022-03-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.CharField(default='', max_length=7),
        ),
    ]
