# Generated by Django 4.0.3 on 2022-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.CharField(default='', max_length=45),
        ),
    ]
