# Generated by Django 4.0.3 on 2022-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.CharField(max_length=7),
        ),
    ]
