# Generated by Django 4.0.3 on 2022-03-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_sales_price_alter_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
