# Generated by Django 4.0.3 on 2022-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0008_alter_sales_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(default='2022-03-14', verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='type',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
